#!/usr/bin/env python3
"""
precompile_shaders.py

Walks the engine shader tree, mirrors the runtime ShaderSource::read_file
splitter (unified .glsl files with #shader vertex/fragment/... directives and
non-recursive #include resolution from shaders/scripts/), runs glslc per stage
followed by spirv-opt --strip-debug, and emits a single C++ source file
containing the SPIR-V blobs plus a registry consumed by the engine at runtime.

The generated file links into the SLViewer executable; the engine library is
unchanged. SLViewer's binary therefore ships with SPIR-V only, no GLSL source.

Usage:
    precompile_shaders.py
        --shaders-root <path/to/ext/Vulkan-Engine/resources/shaders>
        --output       <path/to/build-dir/embedded_shaders.cpp>
        --glslc        <path/to/glslc>
        --spirv-opt    <path/to/spirv-opt>
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# Map a #shader directive token -> (glslc -fshader-stage value, Vk stage enum).
STAGES = [
    ("vertex",      "vert", "VK_SHADER_STAGE_VERTEX_BIT"),
    ("fragment",    "frag", "VK_SHADER_STAGE_FRAGMENT_BIT"),
    ("geometry",    "geom", "VK_SHADER_STAGE_GEOMETRY_BIT"),
    ("tesscontrol", "tesc", "VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT"),
    ("tesseval",    "tese", "VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT"),
    ("compute",     "comp", "VK_SHADER_STAGE_COMPUTE_BIT"),
]
STAGE_TOKENS = [s[0] for s in STAGES]


def split_unified_shader(src_path: Path, scripts_dir: Path):
    """Mirror ShaderSource::read_file: split by #shader, inline #include from scripts/."""
    sections = {tok: [] for tok, _, _ in STAGES}
    current = None

    with open(src_path, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.lstrip()
            if stripped.startswith("#shader"):
                current = next((tok for tok in STAGE_TOKENS if tok in stripped), None)
                continue
            if current is None:
                # Pre-directive header; engine drops these silently. Skip.
                continue
            if stripped.startswith("#include"):
                m = re.match(r"#include\s+(\S+)", stripped)
                if not m:
                    sections[current].append(line)
                    continue
                inc_name = m.group(1).strip().strip('"<>')
                inc_path = scripts_dir / inc_name
                if not inc_path.is_file():
                    raise RuntimeError(
                        f"{src_path}: include not found: {inc_path}"
                    )
                with open(inc_path, "r", encoding="utf-8") as inc:
                    sections[current].append(inc.read())
                    sections[current].append("\n")
                continue
            sections[current].append(line)

    return {tok: "".join(buf) for tok, buf in sections.items() if buf}


def compile_stage(glslc: str, spirv_opt: str, src_text: str,
                  stage_token: str, glslc_stage: str, debug_name: str):
    """Pipe `src_text` through glslc then spirv-opt --strip-debug. Return SPIR-V bytes."""
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        glsl_in  = td / f"{debug_name}.{glslc_stage}.glsl"
        spv_raw  = td / f"{debug_name}.{glslc_stage}.spv"
        spv_opt  = td / f"{debug_name}.{glslc_stage}.opt.spv"

        glsl_in.write_text(src_text, encoding="utf-8")

        # glslc — Vulkan 1.3 / SPIR-V 1.4 to match ShaderSource::compile_shader.
        subprocess.run(
            [glslc, "--target-env=vulkan1.3", "--target-spv=spv1.4",
             f"-fshader-stage={glslc_stage}",
             "-O",
             "-o", str(spv_raw), str(glsl_in)],
            check=True,
        )
        # spirv-opt --strip-debug — removes OpName / OpSource so spirv-cross
        # reconstructs with generic identifiers (_42, _137, ...) instead of ours.
        subprocess.run(
            [spirv_opt, "--strip-debug", "-o", str(spv_opt), str(spv_raw)],
            check=True,
        )

        return spv_opt.read_bytes()


def emit_cpp(entries, output_path: Path):
    """Generate the C++ source. Each blob is a uint32_t[] in an anonymous namespace.
       A static AutoRegister constructor wires the registry into the engine."""
    lines = []
    lines.append("// Generated by tools/precompile_shaders.py. DO NOT EDIT.")
    lines.append("// Embeds pre-compiled SPIR-V for every engine shader; bound to the")
    lines.append("// SLViewer target so it can run without shipping resources/shaders/.")
    lines.append("")
    lines.append("#include <engine/core/shader_registry.h>")
    lines.append("#include <cstdint>")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace {")
    lines.append("")

    for symbol, blob, *_ in entries:
        words = []
        for i in range(0, len(blob), 4):
            words.append("0x{:08x}u".format(int.from_bytes(blob[i:i+4], "little")))
        lines.append(f"alignas(uint32_t) const uint32_t {symbol}[] = {{")
        # 8 words per line keeps the generated file readable in a diff viewer.
        for i in range(0, len(words), 8):
            lines.append("    " + ", ".join(words[i:i+8]) + ",")
        lines.append("};")
        lines.append("")

    lines.append("const VKFW::EmbeddedShaderEntry kEntries[] = {")
    for symbol, _, rel_path, vk_stage in entries:
        lines.append(
            f'    {{ "{rel_path}", {vk_stage}, {symbol}, '
            f'sizeof({symbol}) / sizeof(uint32_t) }},'
        )
    lines.append("};")
    lines.append("")
    lines.append("struct AutoRegister {")
    lines.append("    AutoRegister() {")
    lines.append("        VKFW::set_embedded_shader_registry(")
    lines.append("            kEntries, sizeof(kEntries) / sizeof(kEntries[0]));")
    lines.append("    }")
    lines.append("};")
    lines.append("static AutoRegister _auto_register;")
    lines.append("")
    lines.append("} // namespace")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--shaders-root", required=True, type=Path)
    ap.add_argument("--output",       required=True, type=Path)
    ap.add_argument("--glslc",        required=True)
    ap.add_argument("--spirv-opt",    required=True)
    args = ap.parse_args()

    shaders_root = args.shaders_root.resolve()
    scripts_dir  = shaders_root / "scripts"
    if not scripts_dir.is_dir():
        print(f"[precompile_shaders] scripts/ not found under {shaders_root}",
              file=sys.stderr)
        return 1

    # Entry shaders = every .glsl except those under scripts/ (includes-only),
    # and files whose name contains " copy" (orphaned editor backups in repo).
    entry_files = []
    for path in shaders_root.rglob("*.glsl"):
        rel = path.relative_to(shaders_root)
        if rel.parts and rel.parts[0] == "scripts":
            continue
        if " copy" in rel.name:
            continue
        entry_files.append(rel)
    entry_files.sort()

    stage_token_to_meta = {tok: (glslc_stage, vk_stage)
                           for tok, glslc_stage, vk_stage in STAGES}

    entries = []
    skipped = []
    for rel in entry_files:
        abs_path = shaders_root / rel
        try:
            sections = split_unified_shader(abs_path, scripts_dir)
        except Exception as e:
            # Missing includes / unreadable file — likely dead code (the runtime
            # ShaderSource::read_file would throw on the same input). Skip so
            # SLViewer still builds; if the runtime ever requests this file,
            # the engine's embedded-registry lookup hard-fails with a clear
            # error rather than crashing on a missing include.
            print(f"[precompile_shaders] WARN {rel}: skipped ({e})",
                  file=sys.stderr)
            skipped.append(str(rel))
            continue

        if not sections:
            print(f"[precompile_shaders] WARN {rel}: no #shader directive, skipping",
                  file=sys.stderr)
            skipped.append(str(rel))
            continue

        # Symbol-safe slug from the relative path.
        symbol_base = "shader_" + re.sub(r"[^a-zA-Z0-9]", "_", str(rel.as_posix()))
        rel_key = "shaders/" + rel.as_posix()

        file_failed = False
        file_entries = []
        for tok, src_text in sections.items():
            if not src_text.strip():
                continue
            glslc_stage, vk_stage = stage_token_to_meta[tok]
            try:
                blob = compile_stage(args.glslc, args.spirv_opt, src_text,
                                     tok, glslc_stage, symbol_base)
            except subprocess.CalledProcessError:
                print(f"[precompile_shaders] WARN {rel} [{tok}]: "
                      "glslc/spirv-opt failed, skipping file",
                      file=sys.stderr)
                file_failed = True
                break

            symbol = f"{symbol_base}_{glslc_stage}"
            file_entries.append((symbol, blob, rel_key, vk_stage))

        if file_failed:
            skipped.append(str(rel))
            continue
        entries.extend(file_entries)

    if not entries:
        print("[precompile_shaders] no shaders compiled — aborting",
              file=sys.stderr)
        return 1

    emit_cpp(entries, args.output)
    total = sum(len(e[1]) for e in entries)
    print(f"[precompile_shaders] {len(entries)} stages compiled, "
          f"{total/1024:.1f} KiB SPIR-V → {args.output}")
    if skipped:
        print(f"[precompile_shaders] {len(skipped)} file(s) skipped: "
              f"{', '.join(skipped)}",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
